### ISSUE TITLE
Possible error with content.data.media.attachment using <Content>

### ISSUE THREAD

**Issue by Bellfalasch** [ItemConsulting/enonic-types#10]
Hi,

If I use this library to validate Content that is a media-type content it looks like it doesn't except `.media.attachment` as something to exist within `content.data`. But if you upload an SVG to Content Studio, it stores some data here. Today we bypass this with a @ts-ignore.

```
import { Content, ContentLibrary } from 'enonic-types/content';
const libContent: ContentLibrary = __non_webpack_require__('/lib/xp/content');

// ...

const attachmentContent: Content = libPortal.getContent<Content>();
log.info(attachmentContent?.data?.media?.attachment); // ts linter doesn't like this row

```

Is this expected? Maybe I'm using it wrong. I'm using 1.4.0 of this lib, but used 0.0.74 before and recently upgrading didn't solve the problem.

<img width="373" alt="Skjermbilde 2020-11-11 kl  10 23 47" src="https://user-images.githubusercontent.com/1465598/98793607-6b17eb00-2408-11eb-9083-2c4f4994daa0.png">

**Comment by tajakobsen** [comment]
Hi,

I think the problem might be that `libPortal.getContent()` shouldn't take `Content` as it's type parameter. Try with [Image](https://github.com/ItemConsulting/enonic-types/blob/main/src/content.ts#L61-L87) instead.

Can this be what you are looking for?

```typescript
import { Content, ContentLibrary, Image } from 'enonic-types/content';

const libContent: ContentLibrary = __non_webpack_require__('/lib/xp/content');

// ...

const attachmentContent: Content<Image> = libPortal.getContent<Image>();
log.info(attachmentContent.data.media.attachment);
```

**Comment by tajakobsen** [comment]
Another little tip. :wink:

If you redefine  `__non_webpack_require__()` to [the one on the readme](https://github.com/ItemConsulting/enonic-types#declare-__non_webpack_require__), you shouldn't need setting the `ContentLibrary` type for `libContent` explicitly since the return type always is correct. 

And you can get type competion on the `string` parameter for `__non_webpack_require__()`.
