### ISSUE TITLE
Types for lib-explorer are incomplete

### ISSUE THREAD

**Issue by mikewoudenberg** [ItemConsulting/enonic-types#22]
The NPM package @item-enonic-types/lib-explorer@3.20.6 only contains `index.d.ts` which references `./client` and `./document` but they are not packaged in the module. I think this can be easily fixed by adding  both files to the package.json `files` section

**Comment by tajakobsen** [comment]
@mikewoudenberg I have deployed it now with a patch version. You might have to add it to your npm dependencies without the `^` in front like this (since it has a patch name):

```json
"@item-enonic-types/lib-explorer": "3.20.6-patch1",
```
