### ISSUE TITLE
Type for node library doesnt correctly mirror the code 

### ISSUE THREAD

**Issue by itemodahl** [ItemConsulting/enonic-types#3]
A couple of things:

There is only two functions directly under lib-node: `connect` and `multiRepoConnect`. The functions `get`, `delete`, `update` etc, should instead be moved into the type of `RepoConnection`. 

Some of the `RepoConnection` functions have either a string or an array of strings as an argument, and depending on what is used, either an object or an array of object is returned. Could this be mirrored in the types?

-Ø

**Comment by tajakobsen** [comment]
Closing task since this was addressed in: 28f95491d29ba33ef0e18b789adb5fcdd3f55801
